services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    working_dir: '/workspace'
    tty: true
    ports:
      - '2222:22'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    volumes:
      - ./:/workspace:delegated
      - sa-frontend-node-modules:/workspace/node_modules
      - sa-frontend-pnpm-store:/workspace/.pnpm-store

volumes:
  sa-frontend-node-modules:
  sa-frontend-pnpm-store:
