/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/semesters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific semester by ID
         * @description Retrieve specific semester by id
         */
        get: operations["getSemesterById"];
        /**
         * Update basic info of a semester
         * @description Updates the name, year, and season of an existing semester
         */
        put: operations["updateSemester"];
        post?: never;
        /**
         * Delete a semester
         * @description Deletes an existing semester by id
         */
        delete: operations["deleteSemester"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/semesters/{id}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update grades of a semester
         * @description Updates the grade information for an existing semester
         */
        put: operations["updateSemesterGrades"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/semesters/{id}/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update dates of a semester
         * @description Updates the start and end dates for an existing semester
         */
        put: operations["updateSemesterDates"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific lecture by ID
         * @description Retrieves a specific lecture by its ID
         */
        get: operations["getLectureById"];
        /**
         * Update a lecture
         * @description Updates an existing lecture
         */
        put: operations["updateLecture"];
        post?: never;
        /**
         * Delete a lecture
         * @description Deletes a specific lecture by its ID
         */
        delete: operations["deleteLecture"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{id}/display-order-lex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update lecture display order lex
         * @description Updates the display order lex of a lecture
         */
        put: operations["updateLectureDisplayOrderLex"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific course by ID
         * @description Retrieve specific course by id
         */
        get: operations["getCourseById"];
        /**
         * Update basic info of a course
         * @description Updates the name of an existing course
         */
        put: operations["updateCourse"];
        post?: never;
        /**
         * Delete a course
         * @description Deletes an existing course by id
         */
        delete: operations["deleteCourse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/courses/{id}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update grades of a course
         * @description Updates the grade information for an existing course
         */
        put: operations["updateCourseGrades"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all semesters for the user
         * @description Retrieves a list of all semesters for a user
         */
        get: operations["getSemesters"];
        put?: never;
        /**
         * Create a new semester
         * @description Creates a new semester
         */
        post: operations["createSemester"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates a new lecture */
        post: operations["createLecture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new course
         * @description Creates a new course
         */
        post: operations["createCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 회원가입
         * @description 이메일과 비밀번호, 이름으로 회원가입을 진행합니다.
         */
        post: operations["signupWithEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description 리프레시 토큰을 통해 액세스 토큰과 리프레시 토큰을 재발급합니다.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 리프레시 토큰을 이용하여 로그아웃합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 로그인
         * @description 이메일과 비밀번호로 로그인합니다.
         */
        post: operations["loginWithEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/semesters/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find a specific semester by year and season
         * @description Retrieves a semester with the year and season
         */
        get: operations["getSemesterByYearAndSeason"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/course/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all lectures for a specific course
         * @description Retrieves a list of all lectures for a specific course
         */
        get: operations["getLecturesByCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/courses/semester/{semesterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all courses for a specific semester
         * @description Retrieves a list of all courses for a specific semester
         */
        get: operations["getCoursesBySemester"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회 (Access Token 유효성 확인용)
         * @description 로그인한 사용자의 정보를 조회하거나, 액세스 토큰 유효성을 확인합니다.
         */
        get: operations["getCurrentUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Update semester request */
        UpdateSemesterRequest: {
            /**
             * @description Name of the semester
             * @example Spring 2024
             */
            name?: string;
            /**
             * Format: int32
             * @description Year of the semester
             * @example 2024
             */
            year?: number;
            /**
             * @description Season of the semester (SPRING, SUMMER, FALL, WINTER)
             * @example SPRING
             */
            season?: string;
        };
        /** @description Semester response */
        SemesterResponse: {
            /**
             * Format: uuid
             * @description Unique ID of the semester
             */
            id: string;
            /**
             * Format: uuid
             * @description Unique ID of the user
             */
            userId: string;
            /** @description Name of the semester */
            name: string;
            /**
             * Format: int32
             * @description Year of the semester
             */
            year: number;
            /**
             * @description Season of the semester (SPRING, SUMMER, FALL, WINTER)
             * @enum {string}
             */
            season: "spring" | "summer" | "fall" | "winter";
            /**
             * Format: date
             * @description Start date of the semester
             */
            startDate?: string;
            /**
             * Format: date
             * @description End date of the semester
             */
            endDate?: string;
            /**
             * Format: float
             * @description Target grade for the semester
             */
            targetGrade?: number;
            /**
             * Format: float
             * @description Earned grade for the semester
             */
            earnedGrade?: number;
            /**
             * Format: int32
             * @description Completed credits for the semester
             */
            completedCredits?: number;
            /**
             * Format: date-time
             * @description Creation timestamp of the semester
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp of the semester
             */
            updatedAt: string;
        };
        /** @description Update semester grades request */
        UpdateSemesterGradesRequest: {
            /**
             * Format: float
             * @description Target grade for the semester
             * @example 4
             */
            targetGrade?: number;
            /**
             * Format: float
             * @description Earned grade for the semester
             * @example 3.5
             */
            earnedGrade?: number;
            /**
             * Format: int32
             * @description Completed credits for the semester
             * @example 15
             */
            completedCredits?: number;
        };
        /** @description Update semester dates request */
        UpdateSemesterDatesRequest: {
            /**
             * Format: date
             * @description Start date of the semester
             * @example 2024-03-01
             */
            startDate?: string;
            /**
             * Format: date
             * @description End date of the semester
             * @example 2024-06-30
             */
            endDate?: string;
        };
        /** @description Lecture update request */
        UpdateLectureRequest: {
            /** @description Updated lecture title */
            title: string;
            /** @description Updated lecture material path */
            materialPath: string;
            /** @description Updated lecture material type */
            materialType: string;
        };
        /** @description Lecture response DTO */
        LectureResponse: {
            /**
             * Format: uuid
             * @description Unique ID of the lecture
             */
            id: string;
            /**
             * Format: uuid
             * @description Unique ID of the course
             */
            courseId: string;
            /**
             * Format: uuid
             * @description Unique ID of the user
             */
            userId: string;
            /** @description Title of the lecture */
            title: string;
            /** @description Path to the lecture material */
            materialPath?: string;
            /** @description Type of the lecture material */
            materialType?: string;
            /** @description Display order lexicographically */
            displayOrderLex?: string;
            parsedText?: components["schemas"]["ParsedText"];
            /** @description Notes associated with the lecture */
            note?: {
                [key: string]: Record<string, never>;
            };
            /** @description Summary of the lecture */
            summary?: {
                [key: string]: Record<string, never>;
            };
            /**
             * @description Summary status of the lecture
             * @enum {string}
             */
            summaryStatus?: "not_started" | "in_progress" | "completed";
            /**
             * Format: date-time
             * @description Creation timestamp of the lecture
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp of the lecture
             */
            updatedAt: string;
        };
        ParsedPage: {
            text?: string;
            /** Format: int32 */
            page_number?: number;
        };
        /** @description Parsed text from PDF */
        ParsedText: {
            pages?: components["schemas"]["ParsedPage"][];
            /** Format: int32 */
            total_pages?: number;
        };
        /** @description Lecture update request */
        UpdateLectureDisplayOrderLexRequest: {
            /** @description Updated lecture display order lex */
            displayOrderLex: string;
        };
        /** @description Course update request */
        UpdateCourseRequest: {
            /** @description Updated course name */
            name: string;
        };
        /** @description Course response */
        CourseResponse: {
            /**
             * Format: uuid
             * @description Unique ID of the course
             */
            id: string;
            /**
             * Format: uuid
             * @description Unique ID of the semester
             */
            semesterId: string;
            /**
             * Format: uuid
             * @description Unique ID of the user
             */
            userId: string;
            /** @description Name of the course */
            name: string;
            /**
             * Format: float
             * @description Target grade for the course
             */
            targetGrade?: number;
            /**
             * Format: float
             * @description Earned grade for the course
             */
            earnedGrade?: number;
            /**
             * Format: int32
             * @description Completed credits for the course
             */
            completedCredits?: number;
            /**
             * Format: date-time
             * @description Creation timestamp of the course
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp of the course
             */
            updatedAt: string;
        };
        /** @description Course grade update request */
        UpdateCourseGradesRequest: {
            /**
             * Format: float
             * @description Updated target grade for the course
             */
            targetGrade?: number;
            /**
             * Format: float
             * @description Updated earned grade for the course
             */
            earnedGrade?: number;
            /**
             * Format: int32
             * @description Updated completed credits for the course
             */
            completedCredits?: number;
        };
        /** @description Create semester request */
        CreateSemesterRequest: {
            /**
             * @description Name of the semester
             * @example Spring 2024
             */
            name?: string;
            /**
             * Format: int32
             * @description Year of the semester
             * @example 2024
             */
            year?: number;
            /**
             * @description Season of the semester (spring, summer,)
             * @example SPRING
             */
            season?: string;
        };
        /** @description Lecture creation request */
        CreateLectureRequest: {
            /**
             * Format: uuid
             * @description ID of the course
             */
            courseId: string;
            /** @description Title of the lecture */
            title: string;
            /** Format: binary */
            file: string;
        };
        /** @description Course creation request */
        CreateCourseRequest: {
            /**
             * Format: uuid
             * @description ID of the semester
             */
            semesterId: string;
            /** @description Name of the course */
            name: string;
        };
        EmailSignupRequest: {
            email?: string;
            password?: string;
            name?: string;
        };
        TokenRefreshRequest: {
            refreshToken?: string;
        };
        LogoutRequest: {
            refreshToken?: string;
        };
        EmailLoginRequest: {
            email?: string;
            password?: string;
        };
        /** @description List of semesters response */
        SemesterListResponse: {
            /** @description List of semesters */
            semesters?: components["schemas"]["SemesterResponse"][];
        };
        /** @description List of lectures response */
        LectureListResponse: {
            /** @description List of lectures response */
            lectures?: components["schemas"]["LectureResponse"][];
        };
        /** @description List of courses response */
        CourseListResponse: {
            /** @description List of course responses */
            courses?: components["schemas"]["CourseResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSemesterById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the semester to retrieve */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved semester */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description User does not have access to this semester */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
        };
    };
    updateSemester: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the semester to update */
                id: string;
            };
            cookie?: never;
        };
        /** @description Updated semester details */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSemesterRequest"];
            };
        };
        responses: {
            /** @description Semester updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description User does not have access to this semester */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
        };
    };
    deleteSemester: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the semester to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Semester deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not have access to this semester */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSemesterGrades: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the semester to update grades for */
                id: string;
            };
            cookie?: never;
        };
        /** @description Updated grade information */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSemesterGradesRequest"];
            };
        };
        responses: {
            /** @description Semester grades updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Invalid grade/credit values */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description User does not have access to this semester */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
        };
    };
    updateSemesterDates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the semester to update dates for */
                id: string;
            };
            cookie?: never;
        };
        /** @description Updated start and end dates */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSemesterDatesRequest"];
            };
        };
        responses: {
            /** @description Semester dates updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Invalid dates (e.g., end date before start date) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description User does not have access to this semester */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
        };
    };
    getLectureById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture to retrieve */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved lecture */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description User does not have access to this lecture */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
        };
    };
    updateLecture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture to update */
                id: string;
            };
            cookie?: never;
        };
        /** @description Lecture details (title, materialPath, materialType) */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLectureRequest"];
            };
        };
        responses: {
            /** @description Successfully updated lecture */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description User does not have access to this lecture */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
        };
    };
    deleteLecture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully deleted lecture */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not have access to this lecture */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateLectureDisplayOrderLex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the lecture to update */
                id: string;
            };
            cookie?: never;
        };
        /** @description Updated lecture display order lex (displayOrderLex) */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLectureDisplayOrderLexRequest"];
            };
        };
        responses: {
            /** @description Successfully updated lecture display order lex */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not have access to this lecture */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCourseById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the course to retrieve */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description User does not have access to this course */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
        };
    };
    updateCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the course to update */
                id: string;
            };
            cookie?: never;
        };
        /** @description Updated course details */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCourseRequest"];
            };
        };
        responses: {
            /** @description Course updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description User does not have access to this course */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
        };
    };
    deleteCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the course to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not have access to this course */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCourseGrades: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the course to update grades for */
                id: string;
            };
            cookie?: never;
        };
        /** @description Updated grade information */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCourseGradesRequest"];
            };
        };
        responses: {
            /** @description Course grades updated successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid grade/credit values */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not have access to this course */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSemesters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved semesters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterListResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterListResponse"];
                };
            };
        };
    };
    createSemester: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Semester details (name, year, season) */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSemesterRequest"];
            };
        };
        responses: {
            /** @description Semester created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Invalid input or semester already exists for given year & season */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
        };
    };
    createLecture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["CreateLectureRequest"];
            };
        };
        responses: {
            /** @description Successfully created lecture */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureResponse"];
                };
            };
        };
    };
    createCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Course details (name, semesterId) */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourseRequest"];
            };
        };
        responses: {
            /** @description Course created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Invalid input or course already exists for given semester */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseResponse"];
                };
            };
        };
    };
    signupWithEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailSignupRequest"];
            };
        };
        responses: {
            /** @description 이메일 회원가입 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 이미 가입된 이메일 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description 토큰 재발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 리프레시 토큰 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 사용자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description 로그아웃 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    loginWithEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailLoginRequest"];
            };
        };
        responses: {
            /** @description 이메일 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 이메일/비밀번호 입력 오류 또는 로그인 방식 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getSemesterByYearAndSeason: {
        parameters: {
            query: {
                /**
                 * @description year
                 * @example 2024
                 */
                year: number;
                /**
                 * @description season (spring, summer, fall, winter)
                 * @example FALL
                 */
                season: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved semester */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Invalid input (e.g., invalid year or season) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Unauthorized access */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SemesterResponse"];
                };
            };
        };
    };
    getLecturesByCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the course */
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved lectures */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureListResponse"];
                };
            };
            /** @description User does not have access to this lecture */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureListResponse"];
                };
            };
            /** @description Lecture not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureListResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LectureListResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getCoursesBySemester: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the semester */
                semesterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved courses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseListResponse"];
                };
            };
            /** @description User does not have access to this semester */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseListResponse"];
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseListResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseListResponse"];
                };
            };
        };
    };
    getCurrentUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 사용자 정보 조회 성공, 액세스 토큰 유효함 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 유효하지 않은 액세스 토큰 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 사용자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
