import createFetchClient, { Middleware } from 'openapi-fetch';
import createClient from 'openapi-react-query';
import type { paths } from '../types/openapi.schema'; // generated by openapi-typescript

const apiMiddleware: Middleware = {
  async onRequest({ request, options }) {
    // Add JWT token to the request headers
    const accessToken = sessionStorage.getItem('access_token');

    if (accessToken) {
      request.headers.set('Authorization', `Bearer ${accessToken}`);
    }
  },
  onResponse({ response }) {
    // Handle the response
    if (response.status === 401) {
      sessionStorage.removeItem('access_token');
      window.location.href = '/login';
      return;
    }
  },
  onError({ error }) {
    // Handle errors
    console.error('API Error:', error);
  },
};

const apiClient = createFetchClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_URL,
  headers: {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  },
  credentials: 'include',
});

apiClient.use(apiMiddleware);

export const api = createClient(apiClient);

export { apiClient };
