import createClient from 'openapi-fetch';
import type { paths } from '../types/openapi.schema'; // generated by openapi-typescript

const apiClient = createClient<paths>({ baseUrl: 'http://localhost:8080/' });

export { apiClient };
